import { InvestmentItemDropdown } from '../models/Item.model';

export const availableCryptoCoins: InvestmentItemDropdown[] = [
	{
		id: 'bitcoin',
		symbol: 'btc',
		name: 'Bitcoin',
		title: 'Bitcoin',
	},
	{
		id: 'ethereum',
		symbol: 'eth',
		name: 'Ethereum',
		title: 'Ethereum',
	},
	{
		id: 'binancecoin',
		symbol: 'bnb',
		name: 'Binance Coin',
		title: 'Binance Coin',
	},
	{
		id: 'tether',
		symbol: 'usdt',
		name: 'Tether',
		title: 'Tether',
	},
	{
		id: 'solana',
		symbol: 'sol',
		name: 'Solana',
		title: 'Solana',
	},
	{
		id: 'usd-coin',
		symbol: 'usdc',
		name: 'USD Coin',
		title: 'USD Coin',
	},
	{
		id: 'cardano',
		symbol: 'ada',
		name: 'Cardano',
		title: 'Cardano',
	},
	{
		id: 'ripple',
		symbol: 'xrp',
		name: 'XRP',
		title: 'XRP',
	},
	{
		id: 'terra-luna',
		symbol: 'luna',
		name: 'Terra',
		title: 'Terra',
	},
	{
		id: 'polkadot',
		symbol: 'dot',
		name: 'Polkadot',
		title: 'Polkadot',
	},
	{
		id: 'avalanche-2',
		symbol: 'AVAX',
		name: 'Avalanche',
		title: 'Avalanche',
	},
	{
		id: 'dogecoin',
		symbol: 'doge',
		name: 'Dogecoin',
		title: 'Dogecoin',
	},
	{
		id: 'shiba-inu',
		symbol: 'shib',
		name: 'Shiba Inu',
		title: 'Shiba Inu',
	},
	{
		id: 'matic-network',
		symbol: 'matic',
		name: 'Polygon',
		title: 'Polygon',
	},
	{
		id: 'binance-usd',
		symbol: 'busd',
		name: 'Binance USD',
		title: 'Binance USD',
	},
	{
		id: 'crypto-com-chain',
		symbol: 'cro',
		name: 'Crypto.com Coin',
		title: 'Crypto.com Coin',
	},
	{
		id: 'wrapped-bitcoin',
		symbol: 'wbtc',
		name: 'Wrapped Bitcoin',
		title: 'Wrapped Bitcoin',
	},
	{
		id: 'litecoin',
		symbol: 'ltc',
		name: 'Litecoin',
		title: 'Litecoin',
	},
	{
		id: 'terrausd',
		symbol: 'ust',
		name: 'TerraUSD',
		title: 'TerraUSD',
	},
	{
		id: 'dai',
		symbol: 'dai',
		name: 'Dai',
		title: 'Dai',
	},
	{
		id: 'chainlink',
		symbol: 'link',
		name: 'Chainlink',
		title: 'Chainlink',
	},
	{
		id: 'algorand',
		symbol: 'algo',
		name: 'Algorand',
		title: 'Algorand',
	},
	{
		id: 'okb',
		symbol: 'okb',
		name: 'OKB',
		title: 'OKB',
	},
	{
		id: 'bitcoin-cash',
		symbol: 'bch',
		name: 'Bitcoin Cash',
		title: 'Bitcoin Cash',
	},
	{
		id: 'tron',
		symbol: 'trx',
		name: 'TRON',
		title: 'TRON',
	},
	{
		id: 'uniswap',
		symbol: 'uni',
		name: 'Uniswap',
		title: 'Uniswap',
	},
	{
		id: 'axie-infinity',
		symbol: 'axs',
		name: 'Axie Infinity',
		title: 'Axie Infinity',
	},
	{
		id: 'cosmos',
		symbol: 'atom',
		name: 'Cosmos',
		title: 'Cosmos',
	},
	{
		id: 'stellar',
		symbol: 'xlm',
		name: 'Stellar',
		title: 'Stellar',
	},
	{
		id: 'staked-ether',
		symbol: 'steth',
		name: 'Lido Staked Ether',
		title: 'Lido Staked Ether',
	},
	{
		id: 'hedera-hashgraph',
		symbol: 'hbar',
		name: 'Hedera',
		title: 'Hedera',
	},
	{
		id: 'compound-ether',
		symbol: 'ceth',
		name: 'cETH',
		title: 'cETH',
	},
	{
		id: 'ftx-token',
		symbol: 'ftt',
		name: 'FTX Token',
		title: 'FTX Token',
	},
	{
		id: 'vechain',
		symbol: 'vet',
		name: 'VeChain',
		title: 'VeChain',
	},
	{
		id: 'near',
		symbol: 'near',
		name: 'Near',
		title: 'Near',
	},
	{
		id: 'filecoin',
		symbol: 'fil',
		name: 'Filecoin',
		title: 'Filecoin',
	},
	{
		id: 'elrond-erd-2',
		symbol: 'egld',
		name: 'Elrond',
		title: 'Elrond',
	},
	{
		id: 'the-sandbox',
		symbol: 'sand',
		name: 'The Sandbox',
		title: 'The Sandbox',
	},
	{
		id: 'ethereum-classic',
		symbol: 'etc',
		name: 'Ethereum Classic',
		title: 'Ethereum Classic',
	},
	{
		id: 'decentraland',
		symbol: 'mana',
		name: 'Decentraland',
		title: 'Decentraland',
	},
	{
		id: 'internet-computer',
		symbol: 'icp',
		name: 'Internet Computer',
		title: 'Internet Computer',
	},
	{
		id: 'cdai',
		symbol: 'cdai',
		name: 'cDAI',
		title: 'cDAI',
	},
	{
		id: 'theta-token',
		symbol: 'theta',
		name: 'Theta Network',
		title: 'Theta Network',
	},
	{
		id: 'magic-internet-money',
		symbol: 'mim',
		name: 'Magic Internet Money',
		title: 'Magic Internet Money',
	},
	{
		id: 'fantom',
		symbol: 'ftm',
		name: 'Fantom',
		title: 'Fantom',
	},
	{
		id: 'tezos',
		symbol: 'xtz',
		name: 'Tezos',
		title: 'Tezos',
	},
	{
		id: 'compound-usd-coin',
		symbol: 'cusdc',
		name: 'cUSDC',
		title: 'cUSDC',
	},
	{
		id: 'gala',
		symbol: 'gala',
		name: 'Gala',
		title: 'Gala',
	},
	{
		id: 'the-graph',
		symbol: 'grt',
		name: 'The Graph',
		title: 'The Graph',
	},
	{
		id: 'monero',
		symbol: 'xmr',
		name: 'Monero',
		title: 'Monero',
	},
	{
		id: 'leo-token',
		symbol: 'leo',
		name: 'LEO Token',
		title: 'LEO Token',
	},
	{
		id: 'helium',
		symbol: 'hnt',
		name: 'Helium',
		title: 'Helium',
	},
	{
		id: 'klay-token',
		symbol: 'klay',
		name: 'Klaytn',
		title: 'Klaytn',
	},
	{
		id: 'eos',
		symbol: 'eos',
		name: 'EOS',
		title: 'EOS',
	},
	{
		id: 'pancakeswap-token',
		symbol: 'cake',
		name: 'PancakeSwap',
		title: 'PancakeSwap',
	},
	{
		id: 'iota',
		symbol: 'miota',
		name: 'IOTA',
		title: 'IOTA',
	},
	{
		id: 'arweave',
		symbol: 'ar',
		name: 'Arweave',
		title: 'Arweave',
	},
	{
		id: 'harmony',
		symbol: 'one',
		name: 'Harmony',
		title: 'Harmony',
	},
	{
		id: 'flow',
		symbol: 'flow',
		name: 'Flow',
		title: 'Flow',
	},
	{
		id: 'loopring',
		symbol: 'lrc',
		name: 'Loopring',
		title: 'Loopring',
	},
	{
		id: 'bittorrent-2',
		symbol: 'btt',
		name: 'BitTorrent',
		title: 'BitTorrent',
	},
	{
		id: 'aave',
		symbol: 'aave',
		name: 'Aave',
		title: 'Aave',
	},
	{
		id: 'kusama',
		symbol: 'ksm',
		name: 'Kusama',
		title: 'Kusama',
	},
	{
		id: 'quant-network',
		symbol: 'qnt',
		name: 'Quant',
		title: 'Quant',
	},
	{
		id: 'radix',
		symbol: 'xrd',
		name: 'Radix',
		title: 'Radix',
	},
	{
		id: 'olympus',
		symbol: 'ohm',
		name: 'Olympus',
		title: 'Olympus',
	},
	{
		id: 'bitcoin-cash-sv',
		symbol: 'bsv',
		name: 'Bitcoin SV',
		title: 'Bitcoin SV',
	},
	{
		id: 'amp-token',
		symbol: 'amp',
		name: 'Amp',
		title: 'Amp',
	},
	{
		id: 'blockstack',
		symbol: 'stx',
		name: 'Stacks',
		title: 'Stacks',
	},
	{
		id: 'enjincoin',
		symbol: 'enj',
		name: 'Enjin Coin',
		title: 'Enjin Coin',
	},
	{
		id: 'maker',
		symbol: 'mkr',
		name: 'Maker',
		title: 'Maker',
	},
	{
		id: 'ecash',
		symbol: 'xec',
		name: 'eCash',
		title: 'eCash',
	},
	{
		id: 'bitcoin-cash-abc-2',
		symbol: 'bcha',
		name: 'Bitcoin Cash ABC',
		title: 'Bitcoin Cash ABC',
	},
	{
		id: 'zcash',
		symbol: 'zec',
		name: 'Zcash',
		title: 'Zcash',
	},
	{
		id: 'theta-fuel',
		symbol: 'tfuel',
		name: 'Theta Fuel',
		title: 'Theta Fuel',
	},
	{
		id: 'huobi-btc',
		symbol: 'hbtc',
		name: 'Huobi BTC',
		title: 'Huobi BTC',
	},
	{
		id: 'thorchain',
		symbol: 'rune',
		name: 'THORChain',
		title: 'THORChain',
	},
	{
		id: 'neo',
		symbol: 'neo',
		name: 'NEO',
		title: 'NEO',
	},
	{
		id: 'kadena',
		symbol: 'kda',
		name: 'Kadena',
		title: 'Kadena',
	},
	{
		id: 'basic-attention-token',
		symbol: 'bat',
		name: 'Basic Attention Token',
		title: 'Basic Attention Token',
	},
	{
		id: 'waves',
		symbol: 'waves',
		name: 'Waves',
		title: 'Waves',
	},
	{
		id: 'kucoin-shares',
		symbol: 'kcs',
		name: 'KuCoin Token',
		title: 'KuCoin Token',
	},
	{
		id: 'curve-dao-token',
		symbol: 'crv',
		name: 'Curve DAO Token',
		title: 'Curve DAO Token',
	},
	{
		id: 'celsius-degree-token',
		symbol: 'cel',
		name: 'Celsius Network',
		title: 'Celsius Network',
	},
	{
		id: 'huobi-token',
		symbol: 'ht',
		name: 'Huobi Token',
		title: 'Huobi Token',
	},
	{
		id: 'frax',
		symbol: 'frax',
		name: 'Frax',
		title: 'Frax',
	},
	{
		id: 'celo',
		symbol: 'celo',
		name: 'Celo',
		title: 'Celo',
	},
	{
		id: 'ecomi',
		symbol: 'omi',
		name: 'ECOMI',
		title: 'ECOMI',
	},
	{
		id: 'spell-token',
		symbol: 'spell',
		name: 'Spell Token',
		title: 'Spell Token',
	},
	{
		id: 'chiliz',
		symbol: 'chz',
		name: 'Chiliz',
		title: 'Chiliz',
	},
	{
		id: 'link',
		symbol: 'ln',
		name: 'LINK',
		title: 'LINK',
	},
	{
		id: 'holotoken',
		symbol: 'hot',
		name: 'Holo',
		title: 'Holo',
	},
	{
		id: 'dash',
		symbol: 'dash',
		name: 'Dash',
		title: 'Dash',
	},
	{
		id: 'convex-finance',
		symbol: 'cvx',
		name: 'Convex Finance',
		title: 'Convex Finance',
	},
	{
		id: 'true-usd',
		symbol: 'tusd',
		name: 'TrueUSD',
		title: 'TrueUSD',
	},
	{
		id: 'msol',
		symbol: 'msol',
		name: 'Marinade staked SOL',
		title: 'Marinade staked SOL',
	},
	{
		id: 'nexo',
		symbol: 'nexo',
		name: 'NEXO',
		title: 'NEXO',
	},
	{
		id: 'compound-governance-token',
		symbol: 'comp',
		name: 'Compound',
		title: 'Compound',
	},
	{
		id: 'decred',
		symbol: 'dcr',
		name: 'Decred',
		title: 'Decred',
	},
	{
		id: 'paxos-standard',
		symbol: 'usdp',
		name: 'Pax Dollar',
		title: 'Pax Dollar',
	},
];
